server.port=8083
spring.datasource.url=jdbc:postgresql://postgres:5432/jansaarthi
spring.datasource.username=jansaarthi
spring.datasource.password=jansaarthi
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret=CHANGE_ME_32_CHAR_MIN_SECRET
security.jwt.issuer=jan-saarthi
security.jwt.audience=jan-saarthi-services
security.jwt.mode=hs256
security.jwt.issuer-uri=http://keycloak:8080/realms/jan-saarthi
spring.config.import=optional:vault://
spring.cloud.vault.uri=http://vault:8200
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN:}
server.ssl.enabled=${MTLS_ENABLED:false}
server.ssl.client-auth=need
server.ssl.key-store=${TLS_KEYSTORE:}
server.ssl.key-store-password=${TLS_KEYSTORE_PASSWORD:}
server.ssl.trust-store=${TLS_TRUSTSTORE:}
server.ssl.trust-store-password=${TLS_TRUSTSTORE_PASSWORD:}
