apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: jansaarthi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: jansaarthi/analytics-service:0.1.0
          ports:
            - containerPort: 8001
          env:
            - name: JWT_SECRET
              value: CHANGE_ME_32_CHAR_MIN_SECRET
            - name: JWT_ISSUER
              value: jan-saarthi
            - name: JWT_AUDIENCE
              value: jan-saarthi-services
            - name: OIDC_JWKS_URL
              value: http://keycloak:8080/realms/jan-saarthi/protocol/openid-connect/certs
            - name: AUTH_MODE
              value: hs256
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_TOKEN
              value: root
            - name: VAULT_SECRET_PATH
              value: secret/data/jansaarthi
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: jansaarthi
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8001
      targetPort: 8001
